// Generated code. DO NOT EDIT!

export enum AchievementCategory {
  Unknown = 0,
  Idol = 1,
  Produce = 2,
  Other = 99,
}
export enum AntiCheatFeatureType {
  Unknown = 0,
  ExamProduceLesson = 1,
  ExamProduceAudition = 2,
  ExamPvpRate = 3,
  ExamTower = 4,
  ExamGvgRaid = 5,
  AndroidPlayIntegrity = 101,
}
export enum AppReviewType {
  Unknown = 0,
  Gasha = 1,
  MainTask = 2,
  Achievement = 3,
  ProduceClear = 4,
}
export enum AssetCopyRuleGroup {
  Unknown = 0,
  Common = 1,
  Motion = 2,
  Voice = 3,
  Camera = 4,
}
export enum AssetCopyRuleType {
  Unknown = 0,
  Require = 1,
  Ignore = 2,
  RequireServer = 3,
  RequireClient = 4,
}
export enum AssetDownloadType {
  Unknown = 0,
  First = 1,
  Second = 2,
}
export enum AssetKind {
  Unknown = 0,
  AssetBundle = 1,
  Resource = 2,
}
export enum AuthProviderType {
  Unknown = 0,
  BandaiNamcoId = 1,
  DmmgamesId = 2,
}
export enum CharacterDetailType {
  Unknown = 0,
  Grade = 1,
  Height = 2,
  Weight = 3,
  BloodType = 4,
  ThreeSize = 5,
  ZodiacSign = 6,
  Cv = 7,
  Age = 8,
  Birthday = 9,
  DominantHand = 10,
  Birthplace = 11,
  SpecialSkill = 12,
  Hobby = 13,
  Introduction = 14,
}
export enum CharacterPersonalityType {
  Unknown = 0,
  A = 1,
  B = 2,
  C = 3,
  D = 4,
}
export enum CoinGashaBoxResetTypeType {
  Unknown = 0,
  EmptyAll = 1,
  EmptyFeature = 2,
  Optional = 3,
}
export enum CoinGashaType {
  Unknown = 0,
  Default = 1,
  Feature = 2,
  Box = 3,
}
export enum ConditionMinMaxType {
  Unknown = 0,
  MinMax = 1,
  Min = 2,
  Max = 3,
}
export enum ConditionOperatorType {
  Unknown = 0,
  And = 1,
  Or = 2,
}
export enum ConditionType {
  Unknown = 0,
  TimeTerm = 1,
  TimeDuration = 2,
  TimeWeekday = 3,
  HomeTime = 4,
  Birthday = 5,
  Login = 6,
  TutorialClear = 7,
  GameStartTutorialClearHour = 8,
  HomeCharacter = 9,
  ProducerLevel = 10,
  Character = 11,
  FanCount = 12,
  DearnessLevel = 13,
  Costume = 14,
  IdolCard = 15,
  DearnessStoryFirstReadTime = 16,
  IdolCardPotentialRank = 17,
  IdolCardLevelLimitRank = 18,
  SupportCard = 19,
  SupportCardLevel = 20,
  SupportCardLevelLimitRank = 21,
  MemoryCount = 22,
  ProduceCard = 23,
  Music = 24,
  CharacterProducePlayCount = 26,
  CharacterProduceClearCount = 27,
  ProduceClearCount = 28,
  ProducePlanClearCount = 29,
  PvpRateOpen = 30,
  PvpRateSeasonPlayCount = 31,
  PvpRateSeasonWinCount = 32,
  PvpRateSeasonRate = 33,
  PvpRateUnitOverallPower = 34,
  WorkCount = 35,
  WorkCharacterCount = 36,
  StoryRead = 37,
  FollowCount = 38,
  CostumeHead = 39,
  GuildJoin = 40,
  MeishiUpdateCount = 41,
  GashaOpen = 42,
  GashaDraw = 43,
  ExchangeItemCount = 44,
  ShopItemPurchase = 45,
  MissionPassProgress = 46,
  MainTaskCompleted = 47,
  MissionCompleted = 48,
  AchievementCompleted = 49,
  ItemObtained = 50,
  ItemCount = 51,
  SeminarExamClear = 53,
  PvpRateSeasonGrade = 54,
  PvpRateBestGrade = 55,
  ProduceStoryRead = 56,
  TowerLayerClear = 57,
  StoryUnlockKeyUse = 58,
  MissionDailyReleaseNotComplete = 59,
  MissionPanelNotComplete = 60,
  AchievementFirstThresholdClearHour = 61,
  MainTaskFirstThresholdClearHour = 62,
  MissionFirstThresholdClearHour = 63,
  PhotoBackground = 64,
  PhotoPose = 65,
  Comeback = 66,
  MissionGroupComplete = 67,
  MissionGroupNotComplete = 68,
  Set = 998,
  NegativeSet = 999,
}
export enum ConsentAgreementType {
  Unknown = 0,
  Unanswered = 1,
  Disagreement = 2,
  Agreement = 3,
}
export enum ConsentType {
  Unknown = 0,
  Overview = 1,
  Analysis = 2,
  Advertisement = 3,
  CustomizedAdvertisement = 4,
  Sns = 5,
}
export enum CostumeFeatureType {
  Unknown = 0,
  Home = 1,
  Produce = 2,
  Live = 3,
  Photography = 4,
}
export enum CostumeMotionType {
  Unknown = 0,
  Wait = 1,
  Start = 2,
  Finish = 3,
  TapReaction = 4,
}
export enum CostumeSetType {
  Unknown = 0,
  Home = 1,
  ProduceSchedule = 2,
  ProduceLive = 3,
  ProduceTraining = 4,
}
export enum CountType {
  Unknown = 0,
  Login = 1,
  ProduceRentalMemory = 2,
  ProduceContinue = 3,
  Achievement = 4,
  ReceivedTotalLoginBonus = 5,
  ConfirmedTotalLoginBonus = 6,
  MeishiUpdate = 7,
  MeishiFollow = 8,
  GuildDonation = 9,
  MainTask = 10,
  AchievementIdol = 11,
  AchievementProduce = 12,
  AchievementOther = 13,
  MainTaskMainStory = 14,
  MainTaskProducer = 15,
  ProduceClearTimeBanWarning = 16,
  MainTaskProducer2 = 100,
  MainTaskProducer3 = 101,
  MainTaskProducer4 = 102,
}
export enum DearnessMotionType {
  Unknown = 0,
  Wait1 = 1,
  Wait2 = 2,
  Reaction = 3,
  ReactionOnce = 4,
  WaitLookAround = 5,
  MultipleTaps = 6,
  Transition = 7,
  WaitOnce = 8,
  WaitLoop = 9,
}
export enum DeckRecommendType {
  Unknown = 0,
  Manual = 1,
  Recommend = 2,
  RecommendAndManual = 3,
  Reset = 4,
}
export enum ErrorCode {
  Unknown = 0,
  InvalidArgument = 1001,
  Internal = 1002,
  Unauthenticated = 1003,
  PermissionDenied = 1004,
  NotFound = 1005,
  OutdatedMasterData = 2001,
  LockFailed = 2002,
  PurchaseRecoverFailed = 2003,
  OutdatedApp = 2004,
  ExchangeNeedRefresh = 2005,
  DateChanged = 2006,
  FriendFollowCountLimitExceeded = 2007,
  FriendFollowersCountLimitExceeded = 2008,
  MeishiFollowCountLimitExceeded = 2009,
  MeishiDuplicatedFollow = 2010,
  UserNotFound = 2011,
  GuildNotFound = 2012,
  GuildAlreadyJoined = 2013,
  GuildDismiss = 2014,
  MeishiNotFound = 2015,
  InvalidPlayIntegrity = 2016,
  InMaintenance = 2017,
  AccountBan = 2018,
  TemporaryAccountBan = 2019,
  PurchaseBan = 2020,
  TemporaryPurchaseBan = 2021,
  RecoveryPurchaseTransactionNotFound = 2022,
  DataUpdated = 2023,
  InFeatureMaintenance = 2024,
  NgWordContains = 2025,
  MigrationBan = 2026,
  TemporaryMigrationBan = 2027,
  InvitationInvalidCode = 2028,
  AuthLinkAccountNotFound = 2029,
  ShopInvalidBirthday = 2030,
  RequestConflict = 2031,
  GameAuthTokenInvalid = 2032,
  OutOfTerm = 2033,
  ConditionInvalid = 2034,
  ShopExceedPurchaseThresholdOnRecover = 2035,
  ShopExceedMaxJewelQuantityOnRecover = 2036,
  ShopExceedPurchaseLimit = 2037,
  UserDataUpdated = 2038,
  DmmGamesIdDuplicated = 2039,
  DmmGamesIdLinkAccountAlreadyExists = 2040,
  DmmGamesIdLocalUserDataNotLinked = 2041,
  ProduceOutdatedRentalSupportCard = 2301,
  ProduceOutdatedRentalMemory = 2302,
  ProduceHistoryNotFound = 2303,
  ProduceUuidInvalid = 2304,
  ProduceNeedReset = 2305,
  ProduceClearTimeBanWarning = 2306,
  GvgRaidStageAlreadyCleared = 3000,
  BnidlinkUserNotFound = 5000,
  BnidlinkMasterDataInvalid = 5001,
}
export enum EventStoryFilterType {
  Unknown = 0,
  StoryEvent = 1,
  SeasonEvent = 2,
  GvgRaid = 3,
}
export enum EventType {
  Unknown = 0,
  MissionDailyRelease = 1,
  MissionPanel = 2,
  ProduceHighScore = 3,
  StoryCampaign = 4,
  StoryEvent = 5,
  StoryEventMainStory = 6,
  StoryEventBoxGasha = 7,
  StoryEventGuildMission = 8,
  GvgRaid = 9,
  DearnessBoost = 10,
}
export enum ExamCommandType {
  Unknown = 0,
  TurnDraw = 1,
  UseHand = 2,
  UseDrink = 3,
  UsePool = 4,
  PlayEffect = 5,
  MovePlayCard = 6,
  TurnCheck = 7,
  PhaseChange = 8,
  SeparateActivity = 9,
  SeparateTrigger = 10,
  NoUsableCardActivity = 11,
  TurnEnd = 12,
  UserCardAfterCheck = 13,
  CardEnchantTrigger = 14,
  SupportCardUpgrade = 15,
  Panic = 16,
}
export enum ExamCostType {
  Unknown = 0,
  ExamLessonBuff = 1,
  ExamReview = 2,
  ExamCardPlayAggressive = 3,
  ExamParameterBuff = 4,
  ExamFullPowerPoint = 5,
  ExamParameterBuffMultiplePerTurn = 6,
}
export enum ExamDescriptionType {
  Unknown = 0,
  CustomizeEffectValue1 = 1,
  CustomizeEffectValue2 = 2,
  CustomizeEffectCount = 3,
  CustomizeTurn = 4,
  CustomizeInitialAdd = 5,
  CustomizePlayMovePositionLost = 6,
  CustomizeEffectAdd = 7,
  CustomizeLessonCountAdd = 8,
  CustomizeCostValue = 9,
  ExamValue = 10,
  ExamValue2 = 11,
  ExamTurn = 12,
  ExamTurnTimer = 13,
  ExamCount = 14,
  ExamCardCreateSearchTurnTimerProduceCardName = 15,
  ExamProduceExamEffect = 16,
  ExamProduceCardSearch = 17,
  CustomizeEffectValuePercent1 = 20,
  CustomizeEffectValuePercent2 = 21,
}
export enum ExamGameType {
  Unknown = 0,
  ProduceLesson = 1,
  ProduceAudition = 2,
  PvpRate = 3,
  Tower = 4,
  GvgRaid = 5,
}
export enum ExamIdolStatusType {
  Unknown = 0,
  Concentration = 1,
  Preservation = 2,
  FullPower = 3,
  OverPreservation = 4,
}
export enum ExamMotionTargetType {
  Unknown = 0,
  VocalLesson = 2,
  DanceLesson = 3,
  VisualLesson = 4,
  VocalLessonHard = 5,
  DanceLessonHard = 6,
  VisualLessonHard = 7,
  Audition = 8,
  Contest = 9,
}
export enum ExamMotionType {
  Unknown = 0,
  ParameterUp = 1,
  ParameterUpLarge = 2,
  BlockAdd = 3,
  Buff = 4,
  Debuff = 5,
  Wait = 6,
  NoMotionUseDrink = 7,
  WaitOnce = 8,
}
export enum ExamOutGameMotionType {
  Unknown = 0,
  Start1 = 1,
  Start2 = 2,
  ResultPerfect = 3,
  ResultSuccess = 4,
  ResultFailure = 5,
  Clear = 6,
}
export enum ExamPhaseType {
  Unknown = 0,
  ExamStandBy = 1,
  TurnStart = 2,
  TurnStartAfter = 3,
  TurnStartDraw = 4,
  Main = 5,
  TurnEnd = 6,
  ExamEnd = 7,
}
export enum ExamPlayType {
  Unknown = 0,
  AutoPlay = 1,
  ManualPlayLesson = 2,
  ManualPlayLessonHard = 3,
  ManualPlayAudition = 4,
}
export enum ExchangeItemCategoryType {
  Unknown = 0,
  All = 1,
  ResourceType = 2,
  ItemType = 3,
  Other = 999,
}
export enum ExchangeItemResetCheckStatus {
  Unknown = 0,
  Open = 1,
  Locked = 2,
}
export enum ExchangeType {
  Unknown = 0,
  Daily = 1,
  Item = 2,
  Event = 3,
}
export enum FeatureMaintenanceType {
  Unknown = 0,
  Exchange = 1,
  Shop = 2,
  Work = 3,
  Mission = 4,
  CoinGasha = 5,
  MissionPass = 6,
  Gasha = 7,
  Guild = 8,
  Produce = 9,
  PvpRate = 10,
  Tower = 11,
  TicketExchange = 12,
  ShopTop = 13,
  StoryEvent = 14,
  ProduceHighScore = 15,
  MissionPanel = 16,
  MissionDailyRelease = 17,
  StoryCampaign = 18,
  GvgRaid = 19,
  Dearness = 20,
}
export enum FriendStatusType {
  Unknown = 0,
  None = 1,
  MutualFollow = 2,
  Follow = 3,
  Follower = 4,
}
export enum GashaAnimationRarity {
  Unknown = 0,
  R = 1,
  Sr = 2,
  Ssr = 3,
  PickupSsridolCard = 4,
}
export enum GashaAnimationStepType {
  Unknown = 0,
  Start = 1,
  Tap = 2,
  Monitor = 3,
  Step1 = 4,
  Step2 = 5,
  Step3 = 6,
  Step4 = 7,
  Freeze = 8,
  FreezeAfter = 9,
  LightList = 10,
  End = 11,
}
export enum GashaButtonAppealType {
  Unknown = 0,
  AppealText = 1,
  DrawableCount = 2,
  CurrentStep = 3,
  FixSsr = 4,
  DiscountDrawableCount = 5,
}
export enum GashaButtonType {
  Unknown = 0,
  Static = 1,
  Dynamic = 2,
}
export enum GashaCardBonusType {
  Unknown = 0,
  All = 1,
  IdolCardAll = 2,
  SupportCardAll = 3,
  IdolCard = 4,
  SupportCard = 5,
}
export enum GashaLimitType {
  Unknown = 0,
  None = 1,
  Total = 2,
  Daily = 3,
  DailyAccumulation = 4,
  DailyLoginAccumulation = 5,
}
export enum GashaType {
  Unknown = 0,
  Default = 1,
  StepUp = 2,
  SelectPickup = 3,
}
export enum GiftFilterType {
  Unknown = 0,
  Jewel = 1,
  IdolCard = 2,
  SupportCard = 3,
  Memory = 4,
  Item = 5,
  Costume = 6,
  Other = 99,
}
export enum GuildActivityPolicyType {
  Unknown = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
  _5 = 5,
  _6 = 6,
}
export enum GuildJoinRequestRouteType {
  Unknown = 0,
  Search = 1,
  Id = 2,
  Suggestion = 3,
}
export enum GuildJoinType {
  Unknown = 0,
  NotJoined = 1,
  Joined = 2,
}
export enum GuildMissionPhaseType {
  Unknown = 0,
  ProduceConditionSet1Unlocked = 1,
  ProduceConditionSet2Unlocked = 2,
  ProduceConditionSet3Unlocked = 3,
  Cleared = 99,
}
export enum GuildNotificationType {
  Unknown = 0,
  Join = 1,
  Dismiss = 2,
}
export enum GuildRoleType {
  Unknown = 0,
  Member = 1,
  Leader = 2,
  JoinRequester = 999,
}
export enum GuildSearchMemberCountRangeType {
  Unknown = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
}
export enum GvgRaidStageIconSizeType {
  Unknown = 0,
  Small = 1,
  Medium = 2,
  Large = 3,
}
export enum HomeLocationType {
  Unknown = 0,
  Home = 1,
  Idol = 2,
  Contest = 3,
  Story1 = 4,
  Story2 = 5,
}
export enum HomeMotionType {
  Unknown = 0,
  Wait1 = 1,
  Wait2 = 2,
  Reaction = 3,
  ReactionOnce = 4,
  WaitLookAround = 5,
  MultipleTaps = 6,
  Transition = 7,
  WaitOnce = 8,
}
export enum HomeTimeType {
  Unknown = 0,
  Morning = 1,
  Daytime = 2,
  Evening = 3,
  Night = 4,
}
export enum HomeType {
  Unknown = 0,
  Home = 1,
  Idol = 2,
  Contest = 3,
  Story = 4,
}
export enum IdolCardDifficultyType {
  Unknown = 0,
  Low = 1,
  Middle = 2,
  High = 3,
}
export enum IdolCardLevelLimitEffectType {
  Unknown = 0,
  ProduceCardUpgrade = 1,
  ProduceVoDaVi = 2,
  ProduceStamina = 3,
  ProduceSkill = 4,
}
export enum IdolCardLevelLimitRank {
  Unknown = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
  _5 = 5,
  _6 = 6,
  _7 = 7,
  _8 = 8,
  _9 = 9,
}
export enum IdolCardPotentialEffectType {
  Unknown = 0,
  ProduceVoDaViGrowthRatePermil = 1,
  ProduceStamina = 2,
  InitialProduceItemChange = 3,
  ProduceSkill = 4,
}
export enum IdolCardPotentialRank {
  Unknown = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
}
export enum IdolCardRarity {
  Unknown = 0,
  R = 1,
  Sr = 2,
  Ssr = 3,
}
export enum IdolSkillPossessionType {
  Unknown = 0,
  IdolSkill1 = 1,
  IdolSkill2 = 2,
  IdolSkill3 = 3,
}
export enum ItemRarity {
  Unknown = 0,
  N = 1,
  R = 2,
  Sr = 3,
  Ssr = 4,
}
export enum ItemType {
  Unknown = 0,
  Money = 1,
  ProduceContinue = 2,
  SupportCardEnhancePoint = 3,
  ActionPointRecovery = 4,
  IdolCardLevelLimitMaterial = 5,
  ProduceRerollMemory = 6,
  GashaTicket = 7,
  Coin = 8,
  ExchangeMaterial = 9,
  Medal = 10,
  IdolCardPiece = 11,
  FriendCoin = 12,
  PvpRateCoin = 13,
  StoryUnlockKey = 14,
  ExchangeTicket = 15,
  ProduceLiveUnlockItem = 16,
  IdolCardPotentialRankUpgrade = 17,
  SupportCardLevelLimitRankUpgrade = 18,
  MemoryInherit = 19,
  DearnessStoryUnlock = 20,
  ProduceBoostRewardSupportCardEnhancePoint = 102,
  ProduceBoostRewardIdolCardLevelLimitMaterial = 103,
}
export enum LangType {
  Unknown = 0,
  Ja = 1,
  Ko = 2,
  ZhTw = 3,
}
export enum LinkType {
  Unknown = 0,
  Story = 1,
  Notice = 2,
  Seminar = 3,
  Produce = 4,
  Memory = 5,
  CoinGasha = 7,
  TicketExchange = 9,
  MissionPass = 10,
  MissionGroup = 11,
  MissionDailyRelease = 12,
  MissionPanel = 13,
  Music = 14,
  Guild = 15,
  Friend = 16,
  MediaMovie = 17,
  MediaComic = 18,
  Invitation = 19,
  PvpRate = 20,
  Meishi = 21,
  StoryEvent = 22,
  ProduceHighScore = 23,
  Tower = 24,
  Gasha = 25,
  ShopJewel = 26,
  ShopPass = 27,
  ShopPack = 28,
  ExchangeDaily = 29,
  ExchangeItem = 30,
  ExchangeEvent = 31,
  MediaFourPanelComic = 32,
  PhotoTop = 33,
  PhotoIdol = 34,
  GvgRaid = 35,
  ShopCostume = 36,
  PhotoLiveSelect = 37,
}
export enum LoginBonusType {
  Unknown = 0,
  Normal = 1,
  Event3D = 2,
  Event2D = 3,
}
export enum MainTaskType {
  Unknown = 0,
  MainStory = 1,
  Producer = 2,
  Producer2 = 3,
  Producer3 = 4,
  Producer4 = 5,
}
export enum MediaType {
  Unknown = 0,
  Movie = 1,
  Comic = 2,
  Other = 3,
  FourPanelComic = 4,
}
export enum MeishiBaseAssetType {
  Unknown = 0,
  StoryBackground = 1,
  CommonBackground = 2,
  Frame = 3,
  Other = 99,
}
export enum MeishiIllustrationType {
  Unknown = 0,
  Idol = 1,
  Sdcharacter = 2,
  IdolSign = 3,
  Logo = 4,
  PictoIcon = 5,
  Other = 99,
}
export enum MeishiObjectType {
  Unknown = 0,
  UserName = 1,
  Achievement = 2,
  Illustration = 3,
  PublicUserId = 4,
  ProducerLevel = 5,
  Comment = 6,
  TotalFanCount = 7,
  PvpRateGrade = 8,
  IdolCardSkin = 9,
  SupportCard = 10,
  ProduceCard = 11,
  ProduceItem = 12,
  ProduceDrink = 13,
  Photo = 14,
  Memory = 15,
  Movie = 16,
  BaseAsset = 17,
  Other = 999,
}
export enum MissionCategory {
  Unknown = 0,
  MainTask = 1,
  Daily = 2,
  Weekly = 3,
  Normal = 4,
  Special = 5,
  Event = 6,
  Achievement = 7,
}
export enum MissionType {
  Unknown = 0,
  IncrementMissionClear = 101,
  IncrementLoginCount = 102,
  IncrementDailyHomeEnterCount = 103,
  IncrementGashaDrawCount = 104,
  IncrementWorkCount = 105,
  IncrementWorkExcellentCount = 106,
  IncrementWorkDurationHour = 107,
  IncrementConsumeActionPoint = 108,
  IncrementShopCoinGashaDrawCount = 109,
  IncrementEventCoinGashaDrawCount = 110,
  IncrementDailyExchangeCount = 111,
  IncrementItemExchangeCount = 112,
  IncrementEventExchangeCount = 113,
  IncrementProvideItemCount = 114,
  IncrementReceiveMoney = 115,
  IncrementIdolCardLevelLimitRankUpdateCount = 121,
  IncrementIdolCardPotentialRankUpdateCount = 122,
  IncrementSupportCardCount = 123,
  IncrementSupportCardLevelUpdateCount = 124,
  IncrementSupportCardLevelLimitRankUpdateCount = 125,
  IncrementFanCount = 134,
  IncrementMemoryGradeCount = 137,
  IncrementMemoryExchangeCount = 138,
  IncrementMeishiUpdateCount = 142,
  IncrementMeishiExchangeCount = 144,
  IncrementMeishiXpostCount = 145,
  IncrementGuildDonationRequestCount = 146,
  IncrementGuildDonationCount = 147,
  IncrementPvpRatePlayCount = 160,
  IncrementPvpRateCharacterPlayCount = 161,
  IncrementPvpRateWinCount = 162,
  IncrementPvpRateCharacterWinCount = 163,
  IncrementPvpRateExamBattleScoreCount = 164,
  IncrementUrlTransition = 165,
  IncrementProfileUpdateCount = 166,
  IncrementPvpRateCharacterExamBattleScoreCount = 167,
  IncrementPhotoIdolCount = 168,
  IncrementGvgRaidChallengeCount = 169,
  IncrementGvgRaidLoopChallengeCount = 170,
  IncrementProduceSupportCardDeckUpdateCount = 201,
  IncrementProduceMemoryDeckUpdateCount = 202,
  IncrementProduceTotalScore = 203,
  IncrementProduceVoteCount = 205,
  IncrementProduceTotalProducePoint = 206,
  IncrementProduceGetProduceCardCount = 207,
  IncrementProduceGetProduceDrinkCount = 208,
  IncrementProduceGetProduceItemCount = 209,
  IncrementProduceTotalAdditionExamBlock = 213,
  IncrementProduceConsumedStamina = 214,
  IncrementProduceExamUseProduceCardCount = 215,
  IncrementProduceCustomizeProduceCardCount = 216,
  IncrementProduceUpgradeProduceCardCount = 217,
  IncrementProduceUseProduceDrinkCount = 218,
  IncrementProduceAdditionParameter = 219,
  IncrementProducePlayCount = 220,
  IncrementProducePlanPlayCount = 221,
  IncrementProduceCharacterPlayCount = 222,
  IncrementProduceIdolCardPlayCount = 223,
  IncrementProduceClearCount = 224,
  IncrementProducePlanClearCount = 225,
  IncrementProduceCharacterClearCount = 226,
  IncrementProduceIdolCardClearCount = 227,
  IncrementProduceSelectStepCount = 228,
  IncrementProduceShopBuyCount = 229,
  IncrementProduceLessonClearCount = 230,
  IncrementProduceGroupSelectStepCount = 231,
  AbsoluteLinkBandaiNamco = 301,
  AbsoluteLoginCount = 302,
  AbsoluteAchievementCount = 303,
  AbsoluteCharacterIdolAchievementCount = 304,
  AbsoluteMainTaskCount = 305,
  AbsoluteProducerLevel = 310,
  AbsoluteIdolCardCount = 311,
  AbsoluteIdolCardLevelLimitRank = 312,
  AbsoluteIdolCardLevelLimitRankCount = 313,
  AbsoluteIdolCardPotentialRankCount = 314,
  AbsoluteSupportCardCount = 315,
  AbsoluteSupportCardLevelCount = 316,
  AbsoluteSupportCardLevelLimitRankCount = 317,
  AbsoluteSupportCardLevel = 319,
  AbsoluteFanCount = 335,
  AbsoluteDearnessLevel = 337,
  AbsoluteMeishiUpdateCount = 343,
  AbsoluteMeishiExchangeCount = 346,
  AbsoluteFollowCount = 348,
  AbsoluteFollowerCount = 349,
  AbsoluteStoryRead = 364,
  AbsoluteGuildJoin = 365,
  AbsolutePvpRateGrade = 366,
  AbsolutePvpRateUnitOverallPower = 367,
  AbsolutePvpRateExamBattleMaxScore = 368,
  AbsolutePvpRateCharacterExamBattleMaxScore = 369,
  AbsolutePvpRateRank = 370,
  AbsoluteTowerTotalClearRank = 371,
  AbsoluteTowerCharacterTotalClearRank = 372,
  AbsoluteTowerClearRank = 373,
  AbsoluteIdolCardSkin = 374,
  AbsoluteSupportCard = 375,
  AbsoluteTowerLayerClear = 376,
  AbsolutePvpRateCurrentGrade = 377,
  AbsoluteLinkSmartphoneWithDmm = 378,
  AbsoluteProduceIdolCardHighScore = 401,
  AbsoluteProducePlanTotalHighScore = 402,
  AbsoluteProducePictureBookProduceCardCount = 410,
  AbsoluteProducePictureBookProduceDrinkCount = 411,
  AbsoluteProducePictureBookProduceItemCount = 412,
  AbsoluteProduceCharacterEnding = 420,
  AbsoluteSeminarExamClear = 421,
  AbsoluteProducePlayCharacterCount = 422,
  AbsoluteProduceStoryRead = 423,
  ConditionClear = 998,
  ProduceConditionClear = 999,
  ProduceConditionClearBeforeLiveEvaluation = 1000,
}
export enum MusicType {
  Unknown = 0,
  Music = 1,
  Instrumental = 2,
  Bgm = 3,
}
export enum MusicWishListRequesterType {
  Unknown = 0,
  Self = 1,
  OtherUser = 2,
  Character = 3,
}
export enum NoticeCategory {
  Unknown = 0,
  Info = 1,
  Bug = 2,
  Pr = 3,
}
export enum NoticeType {
  Unknown = 0,
  Update = 1,
  Gasha = 2,
  Campaign = 3,
  Event = 4,
  Important = 5,
  Information = 6,
  Maintenance = 7,
  Bug = 8,
}
export enum PaymentPendingReceiptDialogTimingType {
  Unknown = 0,
  Skip = 1,
  Daily = 2,
}
export enum PhotoBackgroundCategory {
  Unknown = 0,
  Gakuen = 1,
  Dormitory = 2,
  Around = 3,
  Other = 99,
}
export enum PhotoBackgroundTimeType {
  Unknown = 0,
  Morning = 1,
  Noon = 2,
  Evening = 3,
  Night = 4,
}
export enum PhotoButtonExecuteType {
  Unknown = 0,
  Click = 1,
  PressStart = 2,
  PressEnd = 3,
}
export enum PhotoLookTargetType {
  Unknown = 0,
  Ng = 1,
  Eye = 2,
  FullBody = 3,
}
export enum PhotoPoseMotionType {
  Unknown = 0,
  Reaction = 1,
  Wait = 2,
}
export enum PlatformType {
  Unknown = 0,
  Ios = 1,
  Android = 2,
  Dmm = 3,
  Other = 999,
}
export enum PreferenceType {
  Unknown = 0,
  PhotoButtonExecuteType = 1,
}
export enum ProduceAdvType {
  Unknown = 0,
  BeforeFinalLessonHard = 1,
  BeforeMid1LessonHard = 2,
  BeforeMid2LessonHard = 3,
  BeforeFinalAuditionRefresh = 10,
  BeforeMid1AuditionRefresh = 11,
  BeforeMid2AuditionRefresh = 12,
  BeforeFinalAuditionSelect = 13,
  BeforeMid1AuditionSelect = 14,
  BeforeMid2AuditionSelect = 15,
  Introduction = 17,
  StepSkip = 18,
  Opening = 19,
  ProduceResultTrueEnd = 20,
  ProduceResultA = 21,
  ProduceResultB = 22,
  ProduceResultC = 23,
  ProduceResultFailedFinal = 24,
  ProduceResultFailedMid1 = 25,
  ProduceResultFailedMid2 = 26,
}
export enum ProduceCampaignType {
  Unknown = 0,
  ActionPointDown = 1,
  MemoryRentalCountUp = 2,
  RewardQuantityUp = 3,
  ProduceResultRewardAdd = 4,
  ProduceResultRewardChange = 5,
  MemoryRerollCountUp = 6,
  MemoryRerollFree = 7,
  Event = 8,
}
export enum ProduceCardCategory {
  Unknown = 0,
  ActiveSkill = 1,
  MentalSkill = 2,
  Trouble = 3,
}
export enum ProduceCardGrowEffectType {
  Unknown = 0,
  LessonAdd = 1,
  LessonReduce = 2,
  LessonCountAdd = 3,
  LessonCountReduce = 4,
  BlockAdd = 5,
  BlockReduce = 6,
  FullPowerPointAdd = 7,
  FullPowerPointReduce = 8,
  CostBuffReduce = 10,
  CostBuffAdd = 11,
  CostReduce = 12,
  CostAdd = 13,
  CostPenetrateReduce = 14,
  CostPenetrateAdd = 15,
  ParameterBuffTurnAdd = 16,
  ParameterBuffTurnReduce = 17,
  LessonBuffAdd = 18,
  LessonBuffReduce = 19,
  ReviewAdd = 20,
  ReviewReduce = 21,
  AggressiveAdd = 22,
  AggressiveReduce = 23,
  CardDrawAdd = 24,
  CardDrawReduce = 25,
  ParameterBuffMultiplePerTurnAdd = 26,
  ParameterBuffMultiplePerTurnReduce = 27,
  StaminaConsumptionDownTurnAdd = 28,
  StaminaConsumptionDownTurnReduce = 29,
  StaminaConsumptionAddTurnAdd = 30,
  StaminaConsumptionAddTurnReduce = 31,
  EffectAdd = 32,
  EffectDelete = 33,
  EffectChange = 34,
  CardStatusEnchantChange = 35,
  PlayTriggerChange = 36,
  PlayEffectTriggerChange = 37,
  PlayMovePositionTypeChange = 38,
  InitialAdd = 39,
  CostLessonBuffReduce = 40,
  CostLessonBuffAdd = 41,
  CostReviewReduce = 42,
  CostReviewAdd = 43,
  CostAggressiveReduce = 44,
  CostAggressiveAdd = 45,
  CostParameterBuffReduce = 46,
  CostParameterBuffAdd = 47,
  CostFullPowerPointReduce = 48,
  CostFullPowerPointAdd = 49,
  LessonDependBlockAdd = 50,
  LessonDependExamCardPlayAggressiveAdd = 51,
  LessonDependExamReviewAdd = 52,
  CostParameterBuffMultiplePerTurnAdd = 53,
  CostParameterBuffMultiplePerTurnReduce = 54,
}
export enum ProduceCardMoveEffectTriggerType {
  Unknown = 0,
  Lost = 1,
  Grave = 2,
  Draw = 3,
  Hold = 4,
}
export enum ProduceCardMovePositionType {
  Unknown = 0,
  Hand = 1,
  DeckFirst = 2,
  DeckLast = 3,
  DeckRandom = 4,
  Grave = 5,
  Lost = 6,
  Hold = 7,
}
export enum ProduceCardOrderType {
  Unknown = 0,
  First = 1,
  Last = 2,
  Random = 3,
}
export enum ProduceCardPositionType {
  Unknown = 0,
  None = 1,
  Hand = 2,
  Deck = 3,
  Grave = 4,
  Lost = 5,
  DeckAll = 6,
  RandomPool = 7,
  Playing = 8,
  PlayHand = 9,
  Target = 11,
  Self = 12,
  Hold = 13,
  DeckGrave = 14,
}
export enum ProduceCardRarity {
  Unknown = 0,
  N = 1,
  R = 2,
  Sr = 3,
  Ssr = 4,
}
export enum ProduceCardSearchStatusType {
  Unknown = 0,
  LostPlay = 1,
  EndTurnLost = 2,
  Initial = 4,
  Restrict = 5,
}
export enum ProduceConditionType {
  Unknown = 0,
  EventOccurred = 1,
  EventNotOccurred = 2,
  SupportCard = 3,
  MemoryCharacter = 4,
  SelectStepCount = 6,
  ProduceCardUpgradeCount = 9,
  ProduceCardDeleteCount = 10,
  CurrentStepCountPermil = 12,
  LessonClearCount = 13,
  CurrentStepCount = 14,
  Vocal = 15,
  Dance = 16,
  Visual = 17,
  Stamina = 18,
  ProducePoint = 20,
  HasProduceCard = 21,
  ProduceCardCount = 22,
  ProduceDrinkCount = 23,
  ProduceItemCount = 24,
  ShopPreviousConsumedProducePoint = 26,
  ShopProduceCardBuyCount = 27,
  ShopProduceItemBuyCount = 28,
  ShopProduceDrinkBuyCount = 29,
  LessonVocalScore = 30,
  LessonDanceScore = 31,
  LessonVisualScore = 32,
  ProduceEffectTypeCount = 33,
  AuditionMid1Score = 34,
  AuditionMid2Score = 35,
  AuditionFinalScore = 36,
  AuditionMid1Pass = 37,
  AuditionMid2Pass = 38,
  AuditionFinalPass = 39,
  SelectStepCountVocalLesson = 43,
  SelectStepCountDanceLesson = 44,
  SelectStepCountVisualLesson = 45,
  SelectableStep = 46,
  NextAuditionBaseVocalPermil = 47,
  NextAuditionBaseDancePermil = 48,
  NextAuditionBaseVisualPermil = 49,
  DearnessLevel = 50,
  ClearProduceAchievement = 51,
  ConditionSet = 52,
  CurrentProduce = 53,
  ProduceScoreGrade = 55,
  ProduceScore = 56,
  Character = 57,
  IdolCard = 58,
  IdolCardExamEffectType = 59,
  LatestAuditionRank = 60,
  LatestAuditionReachForceEndScore = 61,
  LatestAuditionBaseScorePermil = 62,
  LatestAuditionExamSkipCount = 63,
  Result = 64,
  NextAuditionEasyBaseVocalPermil = 65,
  NextAuditionEasyBaseDancePermil = 66,
  NextAuditionEasyBaseVisualPermil = 67,
  ProduceCardGet = 68,
  ProduceDrinkGet = 69,
  ProduceItemGet = 70,
  ProduceCardUseCount = 71,
  ProduceDrinkUseCount = 72,
  ProduceItemUseCount = 73,
  ExamTriggerCount = 74,
  LessonExamTriggerCount = 75,
  AuditionExamTriggerCount = 76,
  IdolCardProducePlanType = 77,
  VoteCount = 78,
  LatestAuditionStepSelectNumber = 79,
  CurrentAuditionStepType = 80,
  CurrentAuditionStepSelectNumber = 81,
  DearnessPoint = 82,
  Set = 998,
  NegativeSet = 999,
}
export enum ProduceDescriptionSwapType {
  Unknown = 0,
  Lesson = 1,
  Audition = 2,
  Contest = 3,
}
export enum ProduceDescriptionType {
  Unknown = 0,
  PlainText = 1,
  ProduceExamEffectType = 2,
  ProduceCardCategory = 3,
  DiffText = 5,
  Exam = 6,
  ProduceCardGrowEffectType = 7,
  ProduceStepType = 8,
  ProduceDescription = 10,
  ProduceDescriptionName = 11,
  ProduceCard = 12,
  ProduceCardAnyUpgradeCount = 13,
  ProduceItem = 14,
  ProduceDrink = 15,
  ExamValue = 30,
  ExamValue2 = 31,
  ExamTurn = 32,
  ExamTurnTimer = 33,
  ExamCount = 34,
  ExamCardCreateSearchTurnTimerProduceCardName = 35,
  ExamProduceExamEffect = 36,
  ExamProduceCardSearch = 37,
}
export enum ProduceDisplayType {
  Unknown = 0,
  Itself = 1,
  Choice = 2,
}
export enum ProduceDrinkRarity {
  Unknown = 0,
  N = 1,
  R = 2,
  Sr = 3,
  Ssr = 4,
}
export enum ProduceEffectType {
  Unknown = 0,
  VocalAddition = 1,
  DanceAddition = 2,
  VisualAddition = 3,
  VocalDown = 4,
  DanceDown = 5,
  VisualDown = 6,
  VocalGrowthRateAddition = 7,
  DanceGrowthRateAddition = 8,
  VisualGrowthRateAddition = 9,
  VocalGrowthRateDown = 10,
  DanceGrowthRateDown = 11,
  VisualGrowthRateDown = 12,
  StaminaRecoverFix = 13,
  StaminaRecoverMultiple = 14,
  StaminaReduceFix = 15,
  StaminaReduceMultiple = 16,
  StaminaSpecify = 17,
  StaminaRecoverValueUp = 18,
  StaminaRecoverValueDown = 19,
  StaminaReduceValueUp = 20,
  StaminaReduceValueDown = 21,
  StaminaRecoverDisable = 22,
  MaxStaminaAddition = 23,
  MaxStaminaReduceFix = 24,
  MaxStaminaReduceMultiple = 25,
  ProducePointReduceFix = 26,
  ProducePointReduceMultiple = 27,
  ProducePointSpecify = 28,
  ProducePointAdditionValueUp = 29,
  ProducePointAdditionValueDown = 30,
  ProducePointReduceValueUp = 31,
  ProducePointReduceValueDown = 32,
  ProduceCardUpgrade = 33,
  ProduceCardDuplicate = 34,
  ProduceCardDuplicateUpgrade = 35,
  ProduceCardChange = 36,
  ProduceCardChangeUpgrade = 37,
  ProduceCardDelete = 38,
  ProducePointAddition = 39,
  ProducePointGetDisable = 40,
  ProduceItemGetDisable = 41,
  ProduceDrinkGetDisable = 42,
  ProduceReward = 43,
  ProduceRewardSet = 44,
  AuditionParameterBonusMultiple = 53,
  LessonSpChangeRatePermilAddition = 54,
  LessonVocalSpChangeRatePermilAddition = 55,
  LessonDanceSpChangeRatePermilAddition = 56,
  LessonVisualSpChangeRatePermilAddition = 57,
  LessonSpChangeRatePermilDown = 58,
  ExamStatusEnchant = 60,
  LessonPresentProduceCardRewardCountUp = 61,
  LessonPresentProduceCardRewardCountDown = 62,
  LessonPresentSearchProduceCardRewardCountUp = 63,
  ShopPriceDiscountMultiple = 65,
  ShopProduceCardPriceDiscountMultiple = 66,
  ShopProduceDrinkPriceDiscountMultiple = 68,
  ShopProduceCardUpgradePriceDiscountMultiple = 69,
  ShopProduceCardUpgradePriceSpecify = 70,
  ShopProduceCardDeletePriceDiscountMultiple = 71,
  ShopProduceCardDeletePriceSpecify = 72,
  ProduceResultRewardMoneyUp = 77,
  ProduceResultRewardSupportCardEnhancePointUp = 79,
  SupportCardEventStaminaRecoverUp = 80,
  SupportCardEventProducePointAdditionValueUp = 81,
  SupportCardEventParameterAdditionValueUp = 82,
  SupportCardEventProbabilityUp = 83,
  LessonPresentProducePointUp = 84,
  LessonPresentProducePointDown = 85,
  SupportCardProduceCardUpgradeProbabilityUp = 86,
  ProduceCardSelectRerollCountUp = 87,
  ProducePointAdditionDisableTrigger = 88,
  LessonLimitUp = 89,
  ParameterLimitUp = 90,
  VocalLimitUp = 91,
  DanceLimitUp = 92,
  VisualLimitUp = 93,
  SupportCardEventProduceCardUpgrade = 94,
  ExamTurnUp = 95,
  ExamTurnDown = 96,
  AuditionNpcEnhance = 97,
  ShopPriceUpMultiple = 98,
  ShopProduceCardPriceUpMultiple = 99,
  ShopProduceDrinkPriceUpMultiple = 100,
  ShopProduceCardUpgradePriceUpMultiple = 101,
  ShopProduceCardDeletePriceUpMultiple = 102,
  EventSchoolStaminaUp = 103,
  EventSchoolStaminaDown = 104,
  EventActivityProducePointUp = 105,
  EventActivityProducePointDown = 106,
  BeforeAuditionRefreshStaminaUp = 107,
  BeforeAuditionRefreshStaminaDown = 108,
  ShopRerollCountUp = 109,
  ProduceCardExcludeCountUp = 110,
  CustomizeProduceCardCountUp = 111,
  CustomizeProduceCardProducePointUpMultiple = 112,
  CustomizeProduceCardProducePointDownMultiple = 113,
  VoteCountAddition = 114,
  EventBusinessVoteCountUp = 115,
  EventBusinessVoteCountDown = 116,
  EventBusinessExcellentPermilUp = 117,
  EventBusinessExcellentPermilDown = 118,
  AuditionVoteCountUp = 119,
  AuditionVoteCountDown = 120,
  SelfLessonStaminaUp = 121,
  SelfLessonStaminaDown = 122,
  HighScoreGoldAddition = 123,
  IdolCardProduceCardCustomizeEnable = 124,
}
export enum ProduceEventCharacterType {
  Unknown = 0,
  Opening = 1,
  AfterStep1 = 2,
  BeforeAuditionMid1 = 3,
  AfterAuditionMid1 = 4,
  AfterStep2 = 5,
  BeforeAuditionMid2 = 6,
  AfterAuditionMid2 = 7,
  BeforeAuditionFinal = 8,
  AfterAuditionFinal = 9,
  Failure = 10,
  Ending = 11,
  AfterStepBeforeAuditionMid1 = 12,
  AfterStepBeforeAuditionMid2 = 13,
  AfterStepBeforeAuditionFinal = 14,
}
export enum ProduceEventSuggestionType {
  Unknown = 0,
  Primary = 1,
  Secondary = 2,
}
export enum ProduceEventType {
  Unknown = 0,
  Activity = 1,
  School = 2,
  Character = 3,
  CharacterGrowth = 4,
  IdolCard = 5,
  SupportCard = 6,
  Business = 7,
}
export enum ProduceExamAutoCardSelectEvaluationType {
  Unknown = 0,
  LessonCoefficient = 1,
  FullPowerPointCoefficient = 2,
  FullPowerPointValue2Coefficient = 3,
}
export enum ProduceExamAutoEvaluationType {
  Unknown = 0,
  Parameter = 1,
  Block = 2,
  Stamina = 3,
  ExamLessonBuff = 4,
  ExamReview = 5,
  ExamCardPlayAggressive = 6,
  ExamParameterBuff = 7,
  ExamStaminaConsumptionDown = 8,
  ExamStaminaConsumptionAdd = 9,
  ExamBlockAddDown = 10,
  ExamGimmickLessonDebuff = 11,
  ExamGimmickParameterDebuff = 12,
  ExamGimmickSleepy = 13,
  ExamGimmickSlump = 14,
  ExamStaminaConsumptionDownFix = 15,
  PlayableValueAdd = 16,
  ParameterBuffMultiplePerTurn = 17,
  ParameterBuffOverTurn = 18,
  ExamExtraTurn = 19,
  ExamConcentration = 20,
  ExamPreservation = 21,
  ExamFullPower = 22,
  ExamFullPowerPointTotal = 23,
  ExamConcentrationCount = 24,
  ExamPreservationCount = 25,
  ExamFullPowerCount = 26,
  HoldCount = 27,
  DrawCardCount = 28,
  RemainTurn = 29,
  ExamAntiDebuff = 30,
  StanceLock = 31,
  ExamBlockRestriction = 32,
  ExamLessonValueMultiple = 33,
  ExamReviewMultiple = 34,
  ExamEnthusiasticAdditive = 35,
  ExamEnthusiasticMultiple = 36,
  ExamFullPowerLessonMultipleAdditive = 37,
  ExamConcentrationLessonMultipleAdditive = 38,
  ExamLessonBuffAdditive = 39,
  ExamParameterBuffAdditive = 40,
  ExamAggressiveAdditive = 41,
  ExamReviewAdditive = 42,
  ExamFullPowerPointAdditive = 43,
  ExamGrowEffectLessonAddAdditive = 44,
  ExamLessonValueMultipleDependReviewOrAggressive = 45,
}
export enum ProduceExamEffectType {
  Unknown = 0,
  ExamLesson = 1,
  ExamParameterBuff = 2,
  ExamBlock = 3,
  ExamCardDraw = 4,
  ExamStaminaConsumptionDown = 5,
  ExamCardCreateId = 6,
  ExamStaminaReduceFix = 7,
  ExamCardMove = 9,
  ExamLessonBuff = 10,
  ExamCardUpgrade = 11,
  ExamBlockValueMultiple = 13,
  ExamPlayableValueAdd = 14,
  ExamLessonBuffMultiple = 15,
  ExamCardStaminaConsumptionChange = 17,
  ExamBlockRestriction = 18,
  ExamLessonDependBlock = 19,
  ExamCardCreateSearch = 21,
  ExamStatusEnchant = 22,
  ExamMultipleLessonBuffLesson = 23,
  ExamForcePlayCardSearch = 24,
  ExamCardStaminaConsumptionDownSpecify = 26,
  ExamStaminaDamage = 27,
  ExamStaminaRecoverFix = 28,
  ExamLessonFix = 29,
  ExamCardDuplicate = 30,
  ExamReview = 31,
  ExamLessonValueChangePerPlay = 32,
  ExamCardStaminaConsumptionReduce = 33,
  ExamReviewValueMultiple = 36,
  ExamCardSearchEffectPlayCountBuff = 38,
  ExamLessonValueMultiple = 39,
  ExamCardPlayAggressive = 42,
  ExamConcentration = 45,
  ExamPreservation = 46,
  ExamFullPower = 47,
  ExamStanceReset = 48,
  ExamFullPowerPoint = 49,
  ExamForecast = 50,
  ExamFullPowerPointReduce = 51,
  ExamLessonAddBlock = 52,
  ExamLessonFullPowerPoint = 56,
  ExamSearchPlayCardStaminaConsumptionChange = 59,
  ExamStaminaReduce = 60,
  ExamUplifting = 62,
  ExamExtraTurn = 63,
  ExamAntiDebuff = 66,
  ExamStaminaConsumptionAdd = 69,
  ExamThresholdDown = 70,
  ExamBlockAddDown = 73,
  ExamBlockAddDownRestriction = 74,
  ExamStaminaRecoverAdd = 76,
  ExamStaminaReduceChange = 77,
  ExamPanic = 78,
  ExamLessonChangeSpecifyLessThan = 81,
  ExamHandHold = 82,
  ExamStaminaConsumptionAddFix = 84,
  ExamStaminaConsumptionAddDown = 85,
  ExamStaminaRecoverRestriction = 86,
  ExamStaminaConsumptionDownAdd = 89,
  ExamGetCardUpgrade = 90,
  ExamStaminaConsumptionDownFix = 93,
  ExamHandGraveCountCardDraw = 98,
  ExamHandGraveCountCardAdd = 99,
  ExamEffectTimer = 103,
  ExamGimmickLessonDebuff = 105,
  ExamGimmickParameterDebuff = 106,
  ExamGimmickSleepy = 107,
  ExamGimmickEnthusiastic = 109,
  ExamGimmickPlayCardLimit = 113,
  ExamGimmickSlump = 114,
  ExamGimmickStartTurnCardDrawDown = 115,
  ExamStaminaRecoverMultiple = 117,
  ExamLessonPerSearchCount = 118,
  ExamBlockFix = 119,
  ExamLessonAddMultipleLessonBuff = 120,
  ExamCardStatusEnchant = 121,
  ExamBlockDown = 122,
  ExamLessonChangeSpecifyMoreThan = 123,
  ExamLessonDependExamReview = 124,
  ExamLessonDependExamCardPlayAggressive = 125,
  ExamReviewDependExamBlock = 126,
  ExamBlockDependExamReview = 127,
  ExamReviewDependExamCardPlayAggressive = 128,
  ExamParameterBuffMultiplePerTurn = 129,
  ExamLessonBuffDependParameterBuff = 130,
  ExamLessonDependParameterBuff = 131,
  ExamLessonAddMultipleParameterBuff = 132,
  ExamBlockPerUseCardCount = 133,
  ExamChainEffect = 140,
  StanceLock = 141,
  ExamLessonDependStamina = 142,
  ExamBlockAddMultipleAggressive = 143,
  ExamLessonDependStaminaConsumptionSum = 144,
  ExamChainEffectPerPassedTurn = 145,
  ExamChainEffectPerRemainTurn = 146,
  ExamLessonDependPlayCardCountSum = 147,
  ExamDebuffRecover = 148,
  ExamAggressiveValueMultiple = 149,
  ExamItemFireLimitAdd = 150,
  ExamReviewReduce = 151,
  ExamAggressiveReduce = 152,
  ExamLessonBuffReduce = 153,
  ExamParameterBuffReduce = 154,
  ExamLessonValueMultipleDown = 155,
  ExamAddGrowEffect = 156,
  ExamParameterBuffPerSearchCount = 157,
  ExamLessonBuffPerSearchCount = 158,
  ExamReviewPerSearchCount = 159,
  ExamAggressivePerSearchCount = 160,
  ExamBlockPerSearchCount = 161,
  ExamFullPowerPointPerSearchCount = 162,
  ExamLessonDependBlockAndSearchCount = 163,
  ExamLessonDependAggressiveAndSearchCount = 164,
  ExamLessonDependReviewAndSearchCount = 165,
  ExamEffectPerSearchCount = 166,
  ExamOverPreservation = 167,
  ExamParameterBuffDependLessonBuff = 168,
  ExamAggressiveDependReview = 169,
  ExamEnthusiasticAdditive = 170,
  ExamEnthusiasticMultiple = 171,
  ExamFullPowerLessonMultipleAdditive = 172,
  ExamConcentrationLessonMultipleAdditive = 173,
  ExamLessonBuffAdditive = 174,
  ExamParameterBuffAdditive = 175,
  ExamAggressiveAdditive = 176,
  ExamReviewAdditive = 177,
  ExamFullPowerPointAdditive = 178,
  ExamGrowEffectLessonAddAdditive = 179,
  ExamParameterBuffMultiplePerTurnReduce = 180,
  ExamLessonValueMultipleDependReviewOrAggressive = 181,
  ExamReviewMultiple = 182,
  ExamMultipleEnthusiasticLesson = 183,
  ExamMultipleConcentrationLesson = 184,
  ExamMultipleFullPowerLesson = 185,
}
export enum ProduceExamFieldStatusType {
  Unknown = 0,
  ParameterBuff = 1,
  StaminaUpMultiple = 4,
  StaminaLessMultiple = 5,
  StaminaConsumptionDown = 9,
  ConcentrationUp = 11,
  PreservationUp = 12,
  FullPowerUp = 13,
  PlayCardRestriction = 16,
  NoBlock = 18,
  PlayCardSkill = 19,
  PlayCardLesson = 20,
  PlayCardSupport = 21,
  TurnProgressUp = 22,
  ConditionThresholdMultiple = 27,
  ConditionThresholdMultipleDown = 28,
  LessonBuffUp = 33,
  BlockUp = 34,
  ReviewUp = 35,
  GimmickLessonDebuffUp = 36,
  GimmickSleepyUp = 37,
  ParameterBuffUp = 38,
  BlockAddDown = 39,
  GimmickParameterDebuff = 40,
  RemainingTurn = 41,
  CardPlayAggressiveUp = 42,
  ParameterLessThan = 43,
  FullPowerPointUp = 44,
  FullPowerPointGetSumUp = 45,
  NoStance = 46,
  StanceChangeCountUp = 47,
  ConcentrationChangeCountUp = 48,
  PreservationChangeCountUp = 49,
  FullPowerChangeCountUp = 50,
  CardSearchCountUp = 51,
  PlayCardSearch = 52,
  ParameterBuffMultiplePerTurnUp = 53,
  EnthusiasticUp = 54,
}
export enum ProduceExamPhaseType {
  Unknown = 0,
  ExamCardDraw = 1,
  ExamCardPlay = 2,
  ExamCardPlayAfter = 3,
  ExamStartTurn = 4,
  ExamEndTurn = 5,
  ExamStartExam = 6,
  ExamCardMove = 7,
  ExamCardAdd = 8,
  ExamLesson = 9,
  ExamForecast = 10,
  ExamSearchCardPlay = 11,
  ExamStanceChange = 12,
  ExamStatusChange = 13,
  ExamTurnCheck = 16,
  ExamUseDrink = 17,
  ExamGetPoint = 18,
  ExamShuffle = 19,
  ExamStaminaReduce = 20,
  ExamTurnTimer = 21,
  ExamTurnInterval = 22,
  ExamPlayCountInterval = 23,
  ExamStaminaReduceCard = 24,
  ExamPlayTurnCountInterval = 25,
  StartPlay = 27,
  StartExamPlay = 28,
  ExamCardMoveHand = 29,
  ExamCardMoveGrave = 30,
  ExamCardMoveLost = 31,
  ExamLessonParameterUp = 33,
  ExamBuffConsume = 34,
  ExamStanceChangeCountInterval = 35,
  ExamStanceChangeCount = 36,
  ExamStanceChangeConcentration = 37,
  ExamStanceChangePreservation = 38,
  ExamStanceChangeFullPower = 39,
  ExamStanceReset = 40,
  ExamTurnSkip = 41,
  ExamEndTurnTimer = 42,
  ExamEndTurnInterval = 43,
  ExamPlayCountIntervalAfter = 44,
  ExamStanceChangeFromConcentration = 45,
  ExamStanceChangeFromPreservation = 46,
  ExamStanceChangeFromFullPower = 47,
  None = 999,
}
export enum ProduceExamResultType {
  Unknown = 0,
  Success = 1,
  Normal = 2,
  Failed = 3,
}
export enum ProduceExamTriggerCheckType {
  Unknown = 0,
  Not = 1,
}
export enum ProduceHighScoreEventType {
  Unknown = 0,
  Normal = 1,
  Rush = 2,
}
export enum ProduceItemEffectType {
  Unknown = 0,
  ProduceEffect = 1,
  ExamStatusEnchant = 2,
}
export enum ProduceItemRarity {
  Unknown = 0,
  N = 1,
  R = 2,
  Sr = 3,
  Ssr = 4,
}
export enum ProduceLiveType {
  Unknown = 0,
  TrueEnd = 1,
  A = 2,
  B = 3,
  C = 4,
  D = 5,
  E = 6,
}
export enum ProduceMemoryProduceCardPhaseType {
  Unknown = 0,
  ProduceStart = 1,
  EndAuditionMid = 2,
}
export enum ProduceParameterType {
  Unknown = 0,
  Vocal = 1,
  Dance = 2,
  Visual = 3,
}
export enum ProducePhaseType {
  Unknown = 0,
  RecoveryStamina = 1,
  CustomizeProduceCard = 3,
  GetProducePoint = 4,
  GetProduceItem = 6,
  GetProduceDrink = 7,
  UseProduceDrink = 8,
  GetProduceCard = 9,
  UpgradeProduceCard = 10,
  DeleteProduceCard = 11,
  ProduceStart = 12,
  StartStep = 13,
  StartCustomize = 14,
  StartShop = 15,
  StartRefresh = 16,
  StartPresent = 17,
  StartLesson = 18,
  EndLessonBeforePresent = 19,
  EndLesson = 20,
  FailedLesson = 21,
  EndStepEventActivity = 22,
  EndStepEventSchool = 23,
  EndStepEventCharacterOpening = 24,
  ChangeProduceCard = 25,
  EndStepEventBusiness = 26,
  EndBeforeAuditionRefresh = 27,
  StartAuditionMid = 42,
  StartAuditionMid1 = 43,
  StartAuditionMid2 = 44,
  StartAuditionFinal = 45,
  StartAudition = 46,
  EndAuditionMid = 47,
  EndAuditionMid1 = 48,
  EndAuditionMid2 = 49,
  EndAuditionFinal = 50,
  EndAudition = 51,
  BuyShopItem = 52,
  BuyShopItemProduceCard = 53,
  BuyShopItemProduceDrink = 54,
  BuyShopItemProduceItem = 55,
  BuyShopItemUpgradeProduceCard = 56,
  BuyShopItemDeleteProduceCard = 57,
  EndPresent = 58,
  EndShop = 59,
}
export enum ProducePickRangeType {
  Unknown = 0,
  Select = 1,
  Random = 2,
  All = 3,
}
export enum ProducePlanType {
  Unknown = 0,
  Common = 1,
  Plan1 = 2,
  Plan2 = 3,
  Plan3 = 4,
}
export enum ProduceProgressAuditionStatusType {
  Unknown = 0,
  ReadyForExamBattle = 1,
  InProgressExamBattle = 2,
  ExamBattleSuccess = 3,
  ExamBattleFailure = 4,
}
export enum ProduceProgressConditionType {
  Unknown = 0,
  StaminaRatio = 1,
  StaminaFix = 2,
  ProducePoint = 3,
  ProduceItemCount = 4,
  ProduceDrinkCount = 5,
  ProduceCardCount = 6,
  Vocal = 7,
  Dance = 8,
  Visual = 9,
  StepNumber = 10,
}
export enum ProduceProgressStatus {
  Unknown = 0,
  OpeningAdv = 1,
  OpeningCharacterDearnessStory = 2,
  CharacterEventOpening = 3,
  SelectNextStep = 4,
  BeforeAuditionRefresh = 5,
  BeforeStepCharacterEvent = 6,
  BeforeStepSupportCardEvent = 7,
  StepAction = 8,
  AfterStepAuditionCharacterEvent = 9,
  AfterStepCharacterGrowthEvent = 10,
  AfterStepCharacterDearnessStory = 11,
  AfterStepIdolCardEvent = 12,
  AfterStepSupportCardEvent = 13,
  AfterStepCharacterEvent = 14,
  StartBeforeLiveEvaluation = 15,
  EndBeforeLiveEvaluation = 16,
  IdolCardEvent = 17,
  CharacterEventFailure = 18,
  CharacterEventEnding = 19,
  BeforeStepCampaignEvent = 20,
  AfterStepCampaignEvent = 21,
  End = 30,
  Result = 31,
  GuildMission = 32,
  EndingCharacterDearnessStory = 33,
  DearnessBoost = 34,
  Finished = 99,
}
export enum ProduceResourceOriginType {
  Unknown = 0,
  Produce = 1,
  IdolCard = 2,
  SupportCard = 3,
  MemoryAbility = 4,
  ProduceCard = 5,
  ProduceItem = 6,
  StepAudition = 10,
  StepEvent = 11,
  StepPresent = 12,
  StepShop = 13,
  ExamGimmick = 14,
}
export enum ProduceResourceType {
  Unknown = 0,
  ProduceCard = 1,
  ProduceItem = 2,
  ProduceDrink = 3,
  ProducePoint = 4,
  Stamina = 5,
  ParameterVocal = 6,
  ParameterDance = 7,
  ParameterVisual = 8,
  Vote = 9,
  HighScoreGold = 100,
  CardUpgrade = 997,
  CardDelete = 998,
  Set = 999,
}
export enum ProduceRewardType {
  Unknown = 0,
  Probability = 1,
  Ratio = 2,
}
export enum ProduceScheduleLocationType {
  Unknown = 0,
  ProducerRoom1 = 1,
  ProducerRoom2 = 2,
  Classroom = 3,
  Rooftop = 4,
  Courtyard = 5,
  ProducerRoom3 = 6,
  ProducerRoom4 = 7,
  Classroom2 = 8,
  Rooftop2 = 9,
  Courtyard2 = 10,
}
export enum ProduceScheduleMotionType {
  Unknown = 0,
  Wait1 = 1,
  Wait2 = 2,
  Reaction = 3,
  ReactionOnce = 4,
}
export enum ProduceScheduleStaminaMotionType {
  Unknown = 0,
  Enough = 1,
  NotEnough = 2,
}
export enum ProduceSkillEffectType {
  Unknown = 0,
  VocalAddition = 100,
  VocalGrowthRateAddition = 101,
  DanceAddition = 200,
  DanceGrowthRateAddition = 201,
  VisualAddition = 300,
  VisualGrowthRateAddition = 301,
  StaminaAddition = 500,
  ProduceRewardSet = 1000,
  ProduceEffect = 1001,
}
export enum ProduceStartMotionType {
  Unknown = 0,
  Reaction = 1,
  Wait = 2,
}
export enum ProduceStepAuditionMotionType {
  Unknown = 0,
  Start = 1,
  Result1 = 2,
  Result2 = 3,
  Result3 = 4,
  Failure = 5,
}
export enum ProduceStepAuditionType {
  Unknown = 0,
  Mid1Easy = 1,
  Mid1Normal = 2,
  Mid1Hard = 3,
  Mid2Easy = 4,
  Mid2Normal = 5,
  Mid2Hard = 6,
  FinalEasy = 7,
  FinalNormal = 8,
  FinalHard = 9,
  FinalVeryHard = 10,
}
export enum ProduceStepBusinessType {
  Unknown = 0,
  ProduceCard = 1,
  ProduceDrink = 2,
  ProducePoint = 3,
  Stamina = 4,
}
export enum ProduceStepFanPresentMotionType {
  Unknown = 0,
  Reaction = 1,
  Wait = 2,
}
export enum ProduceStepLessonType {
  Unknown = 0,
  Lesson = 1,
  LessonNormal = 2,
  LessonSp = 3,
  LessonHard = 4,
  LessonVocal = 5,
  LessonDance = 6,
  LessonVisual = 7,
  LessonVocalNormal = 8,
  LessonVocalSp = 9,
  LessonVocalHard = 10,
  LessonDanceNormal = 11,
  LessonDanceSp = 12,
  LessonDanceHard = 13,
  LessonVisualNormal = 14,
  LessonVisualSp = 15,
  LessonVisualHard = 16,
}
export enum ProduceStepPhaseType {
  Unknown = 0,
  Before = 1,
  After = 2,
}
export enum ProduceStepType {
  Unknown = 0,
  LessonVocalNormal = 1,
  LessonVocalSp = 2,
  LessonVocalHard = 3,
  LessonDanceNormal = 4,
  LessonDanceSp = 5,
  LessonDanceHard = 6,
  LessonVisualNormal = 7,
  LessonVisualSp = 8,
  LessonVisualHard = 9,
  Event = 10,
  EventActivity = 11,
  EventSchool = 12,
  Shop = 13,
  Refresh = 14,
  Present = 15,
  AuditionMid1 = 16,
  AuditionMid2 = 17,
  AuditionFinal = 18,
  SelfLessonVocalNormal = 19,
  SelfLessonVocalSp = 20,
  SelfLessonDanceNormal = 21,
  SelfLessonDanceSp = 22,
  SelfLessonVisualNormal = 23,
  SelfLessonVisualSp = 24,
  Business = 25,
  EventBusiness = 26,
  FanPresent = 27,
  Customize = 28,
}
export enum ProduceStoryType {
  Unknown = 0,
  Dearness = 1,
  Character = 2,
  CharacterGrowth = 3,
  IdolCard = 4,
  SupportCard = 5,
  StepActivityEvent = 6,
  StepSchoolEvent = 7,
  Campaign = 8,
  StepBusinessEvent = 9,
}
export enum ProduceTriggerOriginType {
  Unknown = 0,
  Character = 1,
  IdolCard = 2,
  SupportCard = 3,
  Memory = 4,
  Event = 5,
  Item = 6,
  Drink = 7,
  Produce = 8,
  DearnessStory = 9,
}
export enum ProduceType {
  Unknown = 0,
  FirstStar = 1,
  NextIdolAudition = 2,
}
export enum ProducerLevelUnlockType {
  Unknown = 0,
  ProduceCard = 1,
  ProduceDrink = 2,
  ShopProduceCardUpgrade = 10,
  ShopProduceCardDelete = 11,
  ProduceCardSelectRerollCount = 12,
  ProduceCardExcludeCount = 13,
}
export enum PurchaseTransactionStatusType {
  Unknown = 0,
  None = 1,
  Initialized = 2,
  InvalidMasterData = 3,
  ChargeFailed = 4,
  ProvideBonusFailed = 5,
  Completed = 999,
}
export enum PushType {
  Unknown = 0,
  ApFull = 1,
  MoneyFull = 2,
  DailyMission = 3,
  Login = 4,
  PvpRateRemainingPlayCount = 5,
  WorkMiniLiveFinish = 101,
  WorkLiveStreamingFinish = 102,
}
export enum PvpRateGrade {
  Unknown = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
  _5 = 5,
  _6 = 6,
  _7 = 7,
  _8 = 8,
}
export enum PvpRateMotionType {
  Unknown = 0,
  Win = 1,
  Lose = 2,
}
export enum PvpRatePhaseType {
  Unknown = 0,
  MatchedRivals = 1,
  BeforeFirstStage = 2,
  BeforeSecondStage = 3,
  BeforeThirdStage = 4,
  Result = 5,
}
export enum PvpRateRivalType {
  Unknown = 0,
  High = 1,
  Middle = 2,
  Low = 3,
}
export enum PvpRateSeasonStatusType {
  Unknown = 0,
  OutOfTerm = 1,
  PrepareStartTerm = 2,
  NotAttended = 3,
  InTerm = 4,
}
export enum PvpRateStageType {
  Unknown = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
}
export enum ResetTimingType {
  Unknown = 0,
  Daily = 1,
  Weekly = 2,
  Monthly = 3,
  Never = 999,
}
export enum ResourceOriginType {
  Unknown = 0,
  IdolCard = 1,
  IdolCardSkin = 2,
  Shop = 3,
}
export enum ResourceType {
  Unknown = 0,
  ProduceCard = 1,
  Item = 2,
  Memory = 3,
  SupportCard = 4,
  IdolCardSkin = 5,
  MissionPassPoint = 6,
  MissionPassPremiumPass = 7,
  ActionPoint = 8,
  UserExp = 9,
  FanCount = 10,
  FriendFollowLimitCount = 11,
  Music = 12,
  CostumeHead = 13,
  Costume = 14,
  MeishiBaseAsset = 15,
  MeishiIllustrationAsset = 16,
  InvitationPoint = 17,
  Story = 18,
  StoryEventPoint = 19,
  PvpRatePlayCount = 20,
  PhotoBackground = 21,
  PhotoPose = 22,
  DearnessPoint = 23,
  JewelTotal = 1100,
  JewelPaidOnly = 1101,
  Set = 9999,
}
export enum ResultGrade {
  Unknown = 0,
  F = 1,
  E = 2,
  D = 3,
  C = 4,
  CPlus = 5,
  B = 6,
  BPlus = 7,
  A = 8,
  APlus = 9,
  S = 10,
  SPlus = 11,
  Ss = 12,
  SsPlus = 13,
  Sss = 14,
  SssPlus = 15,
}
export enum ResultGradeType {
  Unknown = 0,
  ProduceScore = 1,
  MemoryParameter = 3,
  ProduceIdolCardParameter = 5,
  ProduceVoteCount = 6,
}
export enum RewardProvideType {
  Unknown = 0,
  PatternA = 1,
  PatternB = 2,
  PatternC = 3,
  PatternD = 4,
  PatternE = 5,
}
export enum RewardSetType {
  Unknown = 0,
  Probability = 1,
  Ratio = 2,
}
export enum RuleType {
  Unknown = 0,
  FundSettlement = 1,
  CommercialTransaction = 2,
  Copyright = 3,
  PrereleaseMaintenance = 4,
}
export enum ServingStatus {
  Unknown = 0,
  UnknownServing = 1,
  Serving = 2,
  NotServing = 3,
  ServiceUnknown = 4,
}
export enum ShopItemLabelType {
  Unknown = 0,
  Sale = 1,
  Recommend = 2,
}
export enum ShopType {
  Unknown = 0,
  Jewel = 1,
  Pass = 2,
  Pack = 3,
  Costume = 4,
}
export enum SkillRarity {
  Unknown = 0,
  R = 1,
  Sr = 2,
  Ssr = 3,
  Ur = 4,
}
export enum StartupNotificationDisplayType {
  Unknown = 0,
  Home = 1,
  Shop = 2,
  StoryEvent = 3,
  ProduceHighScore = 4,
  Tower = 5,
  MissionPanel = 6,
  MissionDailyRelease = 7,
  StoryCampaign = 8,
  ProduceResult = 9,
  GvgRaid = 10,
}
export enum StartupNotificationEffectType {
  Unknown = 0,
  Confetti1 = 1,
  Confetti2 = 2,
  Twinkling1 = 3,
}
export enum StartupNotificationType {
  Unknown = 0,
  Movie = 1,
  Adv = 2,
  Image = 3,
  Notice = 4,
  Shop = 5,
  ProfileReport = 6,
}
export enum StoryCampaignType {
  Unknown = 0,
  Event = 1,
  DearnessStory = 2,
}
export enum StoryEventMotionType {
  Unknown = 0,
  Wait = 1,
  Reaction = 2,
  ReactionOnce = 3,
}
export enum StoryEventType {
  Unknown = 0,
  Normal = 1,
  BoxGasha = 2,
  MainStory = 3,
  GuildMission = 4,
}
export enum StoryType {
  Unknown = 0,
  Main = 1,
  CampaignDearnessStory = 2,
  Birthday = 3,
  ExtraDearnessStory = 4,
  DearnessStory = 5,
  AprilFool = 6,
  StoryEvent = 9,
  GvgRaid = 10,
  ProduceHighScore = 11,
  Other = 99,
}
export enum SupportCardLevelLimitRank {
  Unknown = 0,
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
}
export enum SupportCardRarity {
  Unknown = 0,
  R = 1,
  Sr = 2,
  Ssr = 3,
}
export enum SupportCardType {
  Unknown = 0,
  Vocal = 1,
  Dance = 2,
  Visual = 3,
  Assist = 4,
}
export enum TermsType {
  Unknown = 0,
  TermsOfService = 1,
  PrivacyPolicy = 2,
  GlobalConsent = 3,
}
export enum TimeType {
  Unknown = 0,
  LastLoginTime = 1,
  WorkLastInitializedTime = 2,
  NoticeInfoViewedTime = 3,
  NoticeBugViewedTime = 4,
  NoticePrviewedTime = 5,
  LastFriendCoinReceiveTime = 6,
  GuildJoinableTime = 10,
  GuildEstablishableTime = 11,
  GuildDonationRequestableTime = 12,
}
export enum TipsType {
  Unknown = 0,
  CharacterDetail = 1,
  CharacterGossip = 2,
  World = 3,
  Help = 4,
  Comic = 5,
}
export enum TutorialCharacterVoiceType {
  Unknown = 0,
  Select = 1,
  Random = 2,
}
export enum TutorialNavigationPositionType {
  Unknown = 0,
  Top = 1,
  Upper = 2,
  Middle = 3,
  Lower = 4,
  Bottom = 5,
}
export enum TutorialNavigationType {
  Unknown = 0,
  Tips = 1,
  Arrow = 2,
  Focus = 3,
  Character = 4,
  Adv = 5,
}
export enum TutorialProduceCommandType {
  Unknown = 0,
  Start = 1,
  Next = 2,
  StepLessonEnd = 3,
  StepPresentReceive = 4,
  StepAuditionExamEnd = 5,
  StepAuditionEnd = 6,
  CheckBeforeLiveProduceEvaluation = 7,
  Result = 8,
}
export enum TutorialType {
  Unknown = 0,
  GameStart = 1,
  MainTask = 2,
  Work = 3,
  IdolCard = 4,
  IdolCardSkin = 5,
  PvpRate = 6,
  CoinGasha = 7,
  MoneyReceive = 8,
  MissionPass = 9,
  Profile = 10,
  Meishi = 11,
  Friend = 12,
  Achievement = 14,
  IdolCardLevelLimitRankUpdate = 15,
  SupportCardLevelUpdate = 16,
  ItemExchange = 17,
  DailyExchange = 18,
  Tower = 19,
  Guild = 20,
  TutorialReceiveIdolCard = 21,
  PhotoTop = 22,
  PhotoIdol = 23,
  PhotoPrepare = 24,
  Photo = 25,
  MeishiEditCustom = 26,
  MeishiEditCustomManual = 27,
  IdolCardSkinUnit = 28,
  DearnessTop = 29,
  DearnessPoint = 30,
  ProduceIdolCardSelect = 100,
  ProduceSupportCardSelect = 101,
  ProduceMemorySelect = 102,
  ProduceSchedule = 103,
  ProduceEvent = 104,
  ProducePresentStep = 105,
  ProduceShopStep = 106,
  ProduceExamGimmick = 107,
  ProduceExamPerfect = 108,
  ProduceBeforeLiveEvaluation = 109,
  ProduceDifficultySelect = 110,
  ProduceCardUpgrade = 111,
  ProduceCardDelete = 112,
  ProduceDrink = 113,
  ProduceCardUpgradeBySupportCard = 114,
  ProduceExamBattle = 115,
  ProduceSupportCardEvent = 116,
  ProduceStepLessonHardBonus = 117,
  ProduceStepLessonPresent = 118,
  ProduceBeforeAuditionRefresh = 119,
  ProduceBeforeLessonHard = 120,
  ProduceChallenge = 121,
  ProduceNextIdolAuditionTop = 122,
  ProduceNextIdolAuditionSchedule = 123,
  ProduceNextIdolAuditionStepAuditionSelect = 124,
  ProduceNextIdolAuditionStepAuditionStart = 125,
  ProduceNextIdolAuditionResult = 126,
  ProduceStepBusiness = 127,
  ProduceStepCustomize = 128,
  ProduceStepFanPresent = 129,
  MissionPanel = 200,
  ProduceHighScore = 201,
  StoryEvent = 202,
  StoryEventMainStroy = 203,
  StoryEventBoxGasha = 204,
  StoryEventGuildMission = 205,
  GvgRaid = 206,
  ProduceNextIdolAuditionMaster = 207,
  ProduceNextIdolAuditionMasterRanking = 208,
}
export enum ViewAreaType {
  Unknown = 0,
  Produce = 1,
  OutGame = 2,
}
export enum VoicePlayScreenType {
  Unknown = 0,
  Home = 1,
  Produce = 2,
  Other = 3,
  IdolCard = 4,
}
export enum Weekday {
  Unknown = 0,
  Sunday = 1,
  Monday = 2,
  Tuesday = 3,
  Wednesday = 4,
  Thursday = 5,
  Friday = 6,
  Saturday = 7,
}
export enum WorkMotionType {
  Unknown = 0,
  CharacterSelectWait = 1,
  CharacterSelectReaction = 2,
  StartNormal = 3,
  StartFine = 4,
  FinishNormal = 5,
  FinishExcellent = 6,
}
export enum WorkType {
  Unknown = 0,
  MiniLive = 1,
  LiveStreaming = 2,
}
